// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using stockz_bucketz_api.Context;

#nullable disable

namespace stockz_bucketz_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240905173839_dates")]
    partial class dates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("stockz_bucketz_api.Models.MonthlyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Monthly")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PortfolioId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("MonthlyRecords");
                });

            modelBuilder.Entity("stockz_bucketz_api.Models.Portfolio", b =>
                {
                    b.Property<string>("PortfolioId")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("AccumulatedEarnings")
                        .HasColumnType("double");

                    b.Property<double>("AcquisitionCost")
                        .HasColumnType("double");

                    b.Property<double>("Patrimony")
                        .HasColumnType("double");

                    b.Property<double>("Profit")
                        .HasColumnType("double");

                    b.Property<double>("Profitability")
                        .HasColumnType("double");

                    b.HasKey("PortfolioId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("stockz_bucketz_api.Models.SaveStocks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfSave")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("SavesStocks");
                });

            modelBuilder.Entity("stockz_bucketz_api.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Cost")
                        .HasColumnType("double");

                    b.Property<double>("Earnings")
                        .HasColumnType("double");

                    b.Property<double>("MediumPrice")
                        .HasColumnType("double");

                    b.Property<string>("PortfolioId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("stockz_bucketz_api.Models.StockBrapi", b =>
                {
                    b.Property<string>("Stock")
                        .HasColumnType("varchar(255)");

                    b.Property<double?>("Change")
                        .HasColumnType("double");

                    b.Property<double>("Close")
                        .HasColumnType("double");

                    b.Property<string>("Logo")
                        .HasColumnType("longtext");

                    b.Property<long?>("Market_Cap")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Sector")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<double?>("Volume")
                        .HasColumnType("double");

                    b.HasKey("Stock");

                    b.ToTable("StocksBrapi");
                });

            modelBuilder.Entity("stockz_bucketz_api.Models.Transaction", b =>
                {
                    b.Property<int>("IdTransaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTransaction"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PortfolioId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double");

                    b.HasKey("IdTransaction");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("stockz_bucketz_api.Models.MonthlyRecord", b =>
                {
                    b.HasOne("stockz_bucketz_api.Models.Portfolio", "Portfolio")
                        .WithMany("MonthlyRecords")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("stockz_bucketz_api.Models.Stock", b =>
                {
                    b.HasOne("stockz_bucketz_api.Models.Portfolio", "Portfolio")
                        .WithMany("Stocks")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("stockz_bucketz_api.Models.Transaction", b =>
                {
                    b.HasOne("stockz_bucketz_api.Models.Portfolio", "Portfolio")
                        .WithMany("Transactions")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("stockz_bucketz_api.Models.Portfolio", b =>
                {
                    b.Navigation("MonthlyRecords");

                    b.Navigation("Stocks");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
